// @flow

// WEB3
export const WEB3_INIT = 'WEB3_INIT'
export const WEB3_ACCOUNTS_LOAD_ALL = 'WEB3_ACCOUNTS_LOAD_ALL'
export const WEB3_ACCOUNTS_SET_MAIN = 'WEB3_ACCOUNTS_SET_MAIN'
export const WEB3_ACCOUNTS_LOAD_BALANCES = 'WEB3_ACCOUNTS_LOAD_BALANCES'


// SIDEBAR
export const SIDEBAR_SEARCH = 'SIDEBAR_SEARCH'
export const SIDEBAR_VIEW_RESIZE_WIDTH = 'SIDEBAR_VIEW_RESIZE_WIDTH'
export const SIDEBAR_VIEW_TOGGLE_UPLOAD = 'SIDEBAR_VIEW_TOGGLE_UPLOAD'


// SETTINGS
export const SETTINGS_INIT = 'SETTINGS_INIT'
export const SETTINGS_UPDATE = 'SETTINGS_UPDATE'
export const SETTINGS_RESET = 'SETTINGS_RESET'
export const SETTINGS_VIEW_SHOW = 'SETTINGS_VIEW_SHOW'
export const SETTINGS_VIEW_HIDE = 'SETTINGS_VIEW_HIDE'
export const SETTINGS_IMPORT_ACCOUNT = 'SETTINGS_IMPORT_ACCOUNT'
export const SETTINGS_GENERATE_RANDOM_ACCOUNT = 'SETTINGS_GENERATE_RANDOM_ACCOUNT'
export const SETTINGS_REMOVE_ACCOUNT = 'SETTINGS_REMOVE_ACCOUNT'


// FILES
export const FILES_FETCH_ALL = 'FILES_FETCH_ALL'
export const FILES_SHOW_ALL = 'FILES_SHOW_ALL'
export const FILES_UPLOAD = 'FILES_UPLOAD'
export const FILES_COMPILE = 'FILES_COMPILE'
export const FILES_RECOMPILE = 'FILES_RECOMPILE'
export const FILES_SAVE = 'FILES_SAVE'
export const FILES_UPDATE = 'FILES_UPDATE'
export const FILES_REMOVE = 'FILES_REMOVE'


// SELECTED_FILE
export const SELECTED_FILE_SET = 'SELECTED_FILE_SET'
export const FILE_GET_CONTRACT_BALANCES = 'FILE_GET_CONTRACT_BALANCES'


// CONTRACT
export const CONTRACT_DEPLOY = 'CONTRACT_DEPLOY'
export const CONTRACT_SHOW_NEW_ADDRESS = 'CONTRACT_SHOW_NEW_ADDRESS'
export const CONTRACT_SELECT_ADDRESS = 'CONTRACT_SELECT_ADDRESS'
export const CONTRACT_BALANCES_LOAD = 'CONTRACT_BALANCES_LOAD'
export const CONTRACT_BALANCES_SET = 'CONTRACT_BALANCES_SET'
export const CONTRACT_SEND_ETHER = 'CONTRACT_SEND_ETHER'
export const CONTRACT_CALL_FUNCTION = 'CONTRACT_CALL_FUNCTION'


// FUNCTION_CALL_RESULTS
export const FUNCTION_CALL_RESULTS_UPDATE = 'FUNCTION_CALL_RESULTS_UPDATE'
export const FUNCTION_CALL_RESULTS_RESET = 'FUNCTION_CALL_RESULTS_RESET'
